### ISSUE TITLE
Istio/K8s manifest formatの確認

### ISSUE THREAD

**Issue by Himalayan-wildcat** [cloudnativedaysjp/cndt2023-handson#158]
第一回の通し会レビューでK8s manifest formatを下記のformatにあわせることになったので確認。沿っていなければ別でissueを作成して対応。

```yaml
apiVersion: ""
kind: ""
metadata: ""
spec: ""
```
